services:
    entrypoint:
        build:
            context: dhscanner.entrypoint
            dockerfile: Dockerfile
            args:
                APPROVED_BEARER_TOKEN_1: ${APPROVED_BEARER_TOKEN_1}
        ports:
            - 443:443
        networks:
            - dhscanner
    frontjs:
        image: orenishdocker/dhscanner-frontjs:x64
        networks:
            - dhscanner
    frontts:
        image: orenishdocker/dhscanner-frontts:x64
        networks:
            - dhscanner
    frontphp:
        build:
            context: dhscanner.0.fronts/php
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontpy:
        build:
            context: dhscanner.0.fronts/py
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontrb:
        build:
            context: dhscanner.0.fronts/rb
            dockerfile: Dockerfile
        networks:
            - dhscanner
    parsers:
        image: orenishdocker/dhscanner-parsers:x64
        networks:
            - dhscanner
    codegen:
        image: orenishdocker/dhscanner-codegen:x64
        networks:
            - dhscanner
    kbgen:
        image: orenishdocker/dhscanner-kbgen:x64
        networks:
            - dhscanner
    queryengine:
        build:
            context: dhscanner.query.engine
            dockerfile: Dockerfile
        networks:
            - dhscanner

networks:
    dhscanner: