services:
    frontjs:
        build:
            context: dhscanner.0.fronts/js
            dockerfile: Dockerfile
        ports:
            - 8000:3000
    frontphp:
        build:
            context: dhscanner.0.fronts/php
            dockerfile: Dockerfile
        ports:
            - 8008:8000
    parserjs:
        build:
            context: dhscanner.parser.js
            dockerfile: Dockerfile
        ports:
            - 8002:3000
    codegen:
        build:
            context: dhscanner.codegen
            dockerfile: Dockerfile
        ports:
            - 8004:3000
    kbgen:
        build:
            context: dhscanner.kbgen
            dockerfile: Dockerfile
        ports:
            - 8005:3000
    queryengine:
        build:
            context: dhscanner.query.engine
            dockerfile: Dockerfile
        ports:
            - 8007:5000
    parsers:
        build:
            context: dhscanner.parsers
            dockerfile: Dockerfile
        ports:
            - 8009:3000