services:
    entrypoint:
        build:
            context: dhscanner.entrypoint
            dockerfile: Dockerfile
            args:
                TZ: ${TZ:-Asia/Jerusalem}
                NUM_APPROVED_URLS: ${NUM_APPROVED_URLS:-1}
                APPROVED_URL_0: ${APPROVED_URL_0:-}
                APPROVED_BEARER_TOKEN_0: ${APPROVED_BEARER_TOKEN_0:-}
        ports:
            - 443:443
        networks:
            - dhscanner
    frontjs:
        build:
            context: dhscanner.0.fronts/js
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontts:
        build:
            context: dhscanner.0.fronts/ts
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontgo:
        build:
            context: dhscanner.0.fronts/go
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontphp:
        build:
            context: dhscanner.0.fronts/php
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontpy:
        build:
            context: dhscanner.0.fronts/py
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontcs:
        build:
            context: dhscanner.0.fronts/cs
            dockerfile: Dockerfile
        networks:
            - dhscanner
    frontrb:
        build:
            context: dhscanner.0.fronts/rb
            dockerfile: Dockerfile
        networks:
            - dhscanner
    parsers:
        image: orenishdocker/dhscanner-parsers:1.0.2-x64
        networks:
            - dhscanner
    codegen:
        image: orenishdocker/dhscanner-codegen:1.0.3-x64
        networks:
            - dhscanner
    kbgen:
        image: orenishdocker/dhscanner-kbgen:1.0.3-x64
        networks:
            - dhscanner
    queryengine:
        image: orenishdocker/dhscanner-pyswipl:x64
        networks:
            - dhscanner

networks:
    dhscanner: