name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: clone dhscanner (with submodules)
        run: |
          docker compose -f compose.rel.x64.yaml up -d

      - name: Wait for dhscanner to be ready
        run: |
          for i in {1..10}; do
            if curl -s -o /dev/null http://127.0.0.1:8000/; then
              echo "server is ready !"
              break
            fi
            echo "waiting for server ..."
            sleep 2
          done

      - name: send GHSL_2023_136 test data to dhscanner
        run: |
          tar -cz tests/GHSL_2023_136 | curl -v -X POST \
            -H "X-Code-Sent-To-External-Server: false" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @- http://127.0.0.1:8000/ > output.GHSL_2023_136.sarif
          cat output.GHSL_2023_136.sarif
          docker compose -f compose.rel.x64.yaml logs entrypoint

      - name: fail if GHSL_2023_136 output sarif is different from expected
        run: |
          set +e
          delta=$(diff output.GHSL_2023_136.sarif tests/expected/GHSL_2023_136.sarif)
          diff_exit=$?
          set -e
          if [ "$diff_exit" -ne 0 ]; then
            echo "$delta"
            exit 1
          fi

      - name: send CVE_2023_50264 test data to dhscanner
        run: |
          tar -cz tests/CVE_2023_50264 | curl -v -X POST \
            -H "X-Code-Sent-To-External-Server: false" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @- http://127.0.0.1:8000/ > output.CVE_2023_50264.sarif
          cat output.CVE_2023_50264.sarif
          docker compose -f compose.rel.x64.yaml logs entrypoint

      - name: fail if CVE_2023_50264 output sarif is different from expected
        run: |
          set +e
          delta=$(diff output.CVE_2023_50264.sarif tests/expected/CVE_2023_50264.sarif)
          diff_exit=$?
          set -e
          if [ "$diff_exit" -ne 0 ]; then
            echo "$delta"
            exit 1
          fi

      - name: send CVE_2023_34105 test data to dhscanner
        run: |
          tar -cz tests/CVE_2023_34105 | curl -v -X POST \
            -H "X-Code-Sent-To-External-Server: false" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @- http://127.0.0.1:8000/ > output.CVE_2023_34105.sarif
          cat output.CVE_2023_34105.sarif
          docker compose -f compose.rel.x64.yaml logs entrypoint

      - name: fail if CVE_2023_34105 output sarif is different from expected
        run: |
          set +e
          delta=$(diff output.CVE_2023_34105.sarif tests/expected/CVE_2023_34105.sarif)
          diff_exit=$?
          set -e
          if [ "$diff_exit" -ne 0 ]; then
            echo "$delta"
            exit 1
          fi

      - name: send CVE_2024_53995 test data to dhscanner
        run: |
          tar -cz tests/CVE_2024_53995 | curl -v -X POST \
            -H "X-Code-Sent-To-External-Server: false" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @- http://127.0.0.1:8000/ > output.CVE_2024_53995.sarif
          cat output.CVE_2024_53995.sarif
          docker compose -f compose.rel.x64.yaml logs entrypoint

      - name: fail if CVE_2024_53995 output sarif is different from expected
        run: |
          set +e
          delta=$(diff output.CVE_2024_53995.sarif tests/expected/CVE_2024_53995.sarif)
          diff_exit=$?
          set -e
          if [ "$diff_exit" -ne 0 ]; then
            echo "$delta"
            exit 1
          fi

      - name: send CVE_2023_38870 test data to dhscanner
        run: |
          tar -cz tests/CVE_2023_38870 | curl -v -X POST \
            -H "X-Code-Sent-To-External-Server: false" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @- http://127.0.0.1:8000/ > output.CVE_2023_38870.sarif
          cat output.CVE_2023_38870.sarif
          docker compose -f compose.rel.x64.yaml logs entrypoint

      - name: fail if CVE_2023_38870 output sarif is different from expected
        run: |
          set +e
          delta=$(diff output.CVE_2023_38870.sarif tests/expected/CVE_2023_38870.sarif)
          diff_exit=$?
          set -e
          if [ "$diff_exit" -ne 0 ]; then
            echo "$delta"
            exit 1
          fi
